name: Sync Bot Code to Temple Bot

on:
  push:
    paths:
      - 'bot/**'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Copy bot folder
        run: |
          mkdir temp-bot
          cp -R bot/ temp-bot/

      - name: Push to 6ol-temple-bot
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source_file: 'temp-bot/bot'
          destination_repo: '4got1en/6ol-temple-bot'
          destination_folder: 'sync'
          user_email: 'bot@6ol.dev'
          user_name: '6ol-bot'
          commit_message: '🔁 Auto-sync bot code from 6ol-core'