name: Protect Charter

on:
  push:
    branches: [main]

jobs:
  guard-charter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect Charter changes
        id: diff
        run: |
          CHANGED=$(git diff --name-only "${{ github.event.before }}" "${{ github.sha }}" \
                    | grep -c 'temple-core/dbd-charter.md' || true)
          echo "changed=$CHANGED" >> "$GITHUB_OUTPUT"

      - name: Block unauthorized edits
        if: steps.diff.outputs.changed == '1'
        run: |
          echo "::error::Direct edits to dbd-charter.md are blocked. Follow the Amendment Process (ยง12)."
          exit 1