name: Auto-Regenerate Manifests

on:
  schedule:
    - cron: '0 3 * * *'   # every day at 03:00 UTC
  workflow_dispatch:     # manual trigger

permissions:
  contents: write       # allow writing back to the repo

jobs:
  regen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Regenerate manifests
        run: npm run regen

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add scrolls/manifest.json rituals/manifest.json journals/manifest.json onthecomeup/manifest.json finance/manifest.json legal/manifest.json navarre/manifest.json
          git diff --quiet || git commit -m "chore: auto-regenerate manifests"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}