# Secret Rotation Reminder Workflow
# Sends a monthly reminder to rotate secrets via Discord webhook

name: Secret Rotation Reminder

on:
  schedule:
    - cron: '0 12 1 * *' # 12:00 UTC on the 1st of every month

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Send secret rotation reminder
        run: |
          if [ -n "$DISCORD_WEBHOOK_URL" ]; then
            curl -H "Content-Type: application/json" \
              -d '{"content": "🔒 Monthly reminder: Please review and rotate your 6ol Core secrets (.env, GitHub, Discord) if needed!"}' \
              "$DISCORD_WEBHOOK_URL"
          else
            echo "No Discord webhook set."
          fi
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
