name: Whisper Scheduler

on:
  schedule:
    - cron: '0 13 * * *' # Every day at 13:00 UTC
  workflow_dispatch:

jobs:
  whisper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
      - name: Run Whisper Scheduler Script
        run: node scripts/whisper-scheduler.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
